import type { PublicUser, Session, User, VerificationPurpose, VerificationToken } from "../types";

/**
 * ---------------------------------------------------------------------------
 * The repository contracts
 * ---------------------------------------------------------------------------
 * Every database adapter (in-memory, MongoDB, whatever comes next) must
 * satisfy these interfaces exactly. Controllers only ever import
 * `userStore`/`sessionStore`/`verificationTokenStore` from `./index`, never
 * a specific adapter — so swapping databases means writing a new file in
 * `./adapters` and pointing the factory in `./index.ts` at it. Nothing else
 * in the app changes.
 * ---------------------------------------------------------------------------
 */

export interface NewUserInput {
  email: string;
  passwordHash: string;
  name: string;
}

export interface NewSessionInput {
  /** Generated by the caller (authController) before signing the refresh
   *  token, since the token itself is bound to this id — the repository
   *  just persists it, it doesn't get to choose it. */
  id: string;
  userId: string;
  refreshToken: string;
  userAgent?: string;
  ttlMs: number;
}

export interface NewVerificationTokenInput {
  /** Generated by the caller, same reasoning as NewSessionInput.id. */
  id: string;
  userId: string;
  tokenHash: string;
  purpose: VerificationPurpose;
  ttlMs: number;
}

export interface UserRepository {
  findByEmail(email: string): Promise<User | null>;
  findById(id: string): Promise<User | null>;
  create(input: NewUserInput): Promise<User>;
  updatePasswordHash(userId: string, passwordHash: string): Promise<User | null>;
  markEmailVerified(userId: string): Promise<User | null>;
}

export interface SessionRepository {
  create(input: NewSessionInput): Promise<Session>;
  findByRefreshToken(refreshToken: string): Promise<Session | null>;
  /** A hit here means the token being presented is stale (already
   *  rotated out) — the signature of a leaked or replayed token. */
  findByPreviousRefreshToken(refreshToken: string): Promise<Session | null>;
  rotate(sessionId: string, newRefreshToken: string, ttlMs: number): Promise<Session | null>;
  revoke(sessionId: string): Promise<void>;
  revokeAllForUser(userId: string): Promise<void>;
}

export interface VerificationTokenRepository {
  create(input: NewVerificationTokenInput): Promise<VerificationToken>;
  findByTokenHash(
    tokenHash: string,
    purpose: VerificationPurpose
  ): Promise<VerificationToken | null>;
  revoke(id: string): Promise<void>;
  /** Called before issuing a new token, so a user can never have more than
   *  one live token per purpose — an old, unused "verify your email" link
   *  should stop working the moment a newer one is requested. */
  revokeAllForUser(userId: string, purpose: VerificationPurpose): Promise<void>;
}

/**
 * Pure, storage-independent helpers. These don't touch a database, so they
 * don't belong to any one adapter — every adapter's output funnels through
 * these the same way.
 */
export function toPublicUser(user: User): PublicUser {
  const { passwordHash: _passwordHash, ...publicUser } = user;
  return publicUser;
}

export function isSessionExpired(session: Session): boolean {
  return new Date(session.expiresAt).getTime() < Date.now();
}

export function isVerificationTokenExpired(token: VerificationToken): boolean {
  return new Date(token.expiresAt).getTime() < Date.now();
}
